# =============================================
# CONFIG COMMUNE — toujours chargée
# =============================================

# Serveur
server.port=8080

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=ecomove-secret-key-2026-certification-eadl4-secure

# App
spring.application.name=ecomove-api