# Serveur
server.port=8080

# Base de données
spring.datasource.url=jdbc:mysql://localhost:3306/ecomove?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=ecomove-secret-key-2026-certification-eadl4-secure

# App
spring.application.name=ecomove-api