# =============================================
# PROFIL DEV — ton PC local
# Activé avec : spring.profiles.active=dev
# =============================================

spring.datasource.url=jdbc:mysql://localhost:3306/ecomove?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=TON_MOT_DE_PASSE_LOCAL

# Afficher les requêtes SQL en dev
spring.jpa.show-sql=true